export type DataSourceStatus = "connected" | "reference" | "credentials_required" | "offline_pipeline" | "temporarily_unavailable";

export type DataSourceRecord = {
  id: string;
  title: string;
  authority: string;
  category: "satellite" | "land" | "electricity" | "water" | "transport" | "soil" | "climate" | "industry" | "materials";
  url: string;
  status: DataSourceStatus;
  access: string;
  coverage: string;
  refresh: string;
  usedFor: string;
  limitation: string;
};

export const dataSources: DataSourceRecord[] = [
  {
    id: "alpha-sentinel-2025",
    title: "Alpha Turkistan Sentinel‑2 L2A mosaic",
    authority: "Copernicus / Alpha Turkistan",
    category: "satellite",
    url: "https://dataspace.copernicus.eu/",
    status: "connected",
    access: "Local 2025 cloud-reduced mosaic",
    coverage: "Turkistan Region · 18 km analytical grid",
    refresh: "Current snapshot: summer 2025",
    usedFor: "NDVI, NDWI, NDRE, NDMI, NDBI, BSI and crop-screening signals",
    limitation: "A single-season mosaic does not replace field sampling or a multi-year crop history.",
  },
  {
    id: "osm-overpass",
    title: "OpenStreetMap infrastructure",
    authority: "OpenStreetMap contributors",
    category: "transport",
    url: "https://www.openstreetmap.org/copyright",
    status: "connected",
    access: "Regional snapshot plus live 30 km discovery",
    coverage: "Mapped power, rail, rivers, canals, industrial sites and quarries",
    refresh: "Regional snapshot: July 2026; live details on selection",
    usedFor: "Distance to mapped infrastructure and visible map overlays",
    limitation: "Presence on the map does not confirm spare capacity, access rights, flow or ownership.",
  },
  {
    id: "nasa-power",
    title: "NASA POWER climatology",
    authority: "NASA Langley Research Center",
    category: "climate",
    url: "https://power.larc.nasa.gov/docs/services/api/temporal/climatology/",
    status: "connected",
    access: "Open point API without an API key",
    coverage: "Temperature, precipitation, solar radiation and 10 m wind",
    refresh: "Climatological baseline",
    usedFor: "Climate context for a selected zone",
    limitation: "Coarse climate context; not a local weather station or irrigation guarantee.",
  },
  {
    id: "inmap-business-api",
    title: "Компании и инвестиционные проекты in-map",
    authority: "in-map.kz",
    category: "industry",
    url: "https://in-map.kz",
    status: "credentials_required",
    access: "Protected server API; Bearer token is stored only in the hosting environment",
    coverage: "Active companies and non-archived investment projects in Turkistan Region",
    refresh: "Live API with five-minute server cache",
    usedFor: "Nearby factories, projects and potential business partners; modest ecosystem bonus in zone ranking",
    limitation: "A nearby company or project is a collaboration lead, not proof of capacity, availability or willingness to partner.",
  },
  {
    id: "inmap-assets",
    title: "Каталог активов in-map",
    authority: "in-map",
    category: "industry",
    url: "https://in-map-kazakhstan-trade-2026.chatgpt-edu-7368.chatgpt.site/",
    status: "connected",
    access: "Published structured catalogue",
    coverage: "Industrial, agricultural, logistics, energy, tourism and bank collateral assets",
    refresh: "Loaded from the live in-map assets catalogue",
    usedFor: "Nearby reusable sites and facilities; district-level business ecosystem signal",
    limitation: "Assets without verified coordinates are displayed at a district reference point and are not treated as exact locations.",
  },
  {
    id: "egov-free-land",
    title: "Free land in Turkistan Region",
    authority: "Open Data Kazakhstan",
    category: "land",
    url: "https://data.egov.kz/datasets/view?index=turkistan_oblysy_boiynsha_bos_",
    status: "credentials_required",
    access: "Official API requires EGOV_API_KEY",
    coverage: "Area, location text and district/city; no parcel polygons",
    refresh: "Quarterly; dataset page updated 6 May 2026",
    usedFor: "Candidate free-land records after credentials are configured",
    limitation: "Text records cannot prove that an analytical grid cell is free.",
  },
  {
    id: "egkn-cadastre",
    title: "Public cadastral map (EGKN)",
    authority: "Government for Citizens",
    category: "land",
    url: "https://map.gov4c.kz/egkn/",
    status: "reference",
    access: "Public verification portal; no confirmed open parcel API",
    coverage: "Parcels, restrictions, cadastral zones and public land layers",
    refresh: "Operator maintained",
    usedFor: "Final ownership, boundary and permitted-use verification",
    limitation: "Investor must verify a concrete parcel in the official system.",
  },
  {
    id: "kegoc-capacity",
    title: "Free transmission capacity of Southern MES",
    authority: "KEGOC",
    category: "electricity",
    url: "https://www.kegoc.kz/ru/electric-power/deyatelnost-kompanii/poryadok-dostupa-k-natsionalnoy-elektricheskoy-seti/",
    status: "reference",
    access: "Official capacity spreadsheets and connection procedure",
    coverage: "Transmission-level substations; local distribution still requires operator data",
    refresh: "Current official reporting period",
    usedFor: "Capacity verification workflow",
    limitation: "A nearby line is not proof that the requested MW can be connected.",
  },
  {
    id: "qazindustry-iz",
    title: "Industrial zones registry",
    authority: "QazIndustry",
    category: "industry",
    url: "https://sez.qazindustry.gov.kz/ru/report/iz",
    status: "reference",
    access: "Public registry",
    coverage: "Official industrial-zone records",
    refresh: "Operator maintained",
    usedFor: "Industrial-site discovery and operator verification",
    limitation: "Published zone existence does not guarantee a free parcel or utility capacity.",
  },
  {
    id: "nsdi",
    title: "National Spatial Data Infrastructure",
    authority: "Ministry of Digital Development of Kazakhstan",
    category: "water",
    url: "https://map.gov.kz/",
    status: "reference",
    access: "Public geospatial portal",
    coverage: "Includes water-protection zones and other government map layers",
    refresh: "Layer dependent",
    usedFor: "Environmental and planning checks",
    limitation: "A stable public machine API for all required layers has not been confirmed.",
  },
  {
    id: "kazhydromet",
    title: "Hydrological observations",
    authority: "Kazhydromet",
    category: "water",
    url: "https://www.kazhydromet.kz/ru/gidrologiya/ezhegodnye-dannye-o-rezhime-i-resursah-poverhnostnyh-vod-sushi-eds",
    status: "reference",
    access: "Official publications and annual hydrological data",
    coverage: "River and reservoir observations",
    refresh: "Publication dependent",
    usedFor: "Water-risk and seasonal context",
    limitation: "No open parcel-level water capacity or water-right feed is available to this site.",
  },
  {
    id: "qazstat-crops",
    title: "Turkistan agricultural statistics",
    authority: "Bureau of National Statistics",
    category: "industry",
    url: "https://stat.gov.kz/ru/region/turkestan/dynamic-tables/1485/",
    status: "reference",
    access: "Public dynamic tables and downloads",
    coverage: "Area, harvest and crop-yield statistics",
    refresh: "Official statistical calendar",
    usedFor: "District-level market and production validation",
    limitation: "Statistics are not parcel-level suitability measurements.",
  },
  {
    id: "fao-gaez",
    title: "Global Agro‑Ecological Zones v5",
    authority: "FAO / IIASA",
    category: "soil",
    url: "https://www.fao.org/gaez/en",
    status: "offline_pipeline",
    access: "Open geospatial datasets",
    coverage: "Crop suitability and potential yield at approximately 1 km",
    refresh: "GAEZ v5 (2025)",
    usedFor: "Future crop-specific agronomic baseline",
    limitation: "Must be downloaded, reprojected and validated before it can alter scores.",
  },
  {
    id: "soilgrids",
    title: "SoilGrids 250 m",
    authority: "ISRIC — World Soil Information",
    category: "soil",
    url: "https://docs.isric.org/globaldata/soilgrids/index.html",
    status: "offline_pipeline",
    access: "Open rasters; REST service is not relied upon",
    coverage: "pH, organic carbon, texture, nitrogen, CEC and bulk density",
    refresh: "Dataset release dependent",
    usedFor: "Future soil-property enrichment",
    limitation: "Global predictions require local laboratory validation and offline caching.",
  },
  {
    id: "worldcover",
    title: "ESA WorldCover 10 m",
    authority: "European Space Agency",
    category: "satellite",
    url: "https://esa-worldcover.org/en/data-access",
    status: "offline_pipeline",
    access: "Open COG/S3/WMS data",
    coverage: "Land-cover classification at 10 m",
    refresh: "Dataset release dependent",
    usedFor: "Exclude built-up, water and unsuitable cover before parcel screening",
    limitation: "Requires offline clipping and change-date validation.",
  },
  {
    id: "copernicus-dem",
    title: "Copernicus DEM GLO‑30",
    authority: "Copernicus Data Space Ecosystem",
    category: "satellite",
    url: "https://dataspace.copernicus.eu/explore-data/data-collections/copernicus-contributing-missions/collections-description/COP-DEM",
    status: "offline_pipeline",
    access: "Registration and offline processing required",
    coverage: "Elevation and derived slope at 30 m",
    refresh: "Dataset release dependent",
    usedFor: "Future slope and drainage constraints",
    limitation: "Elevation alone does not confirm earthworks cost or flood safety.",
  },
  {
    id: "global-atlases",
    title: "Global Solar and Wind Atlases",
    authority: "World Bank / ESMAP and DTU",
    category: "climate",
    url: "https://globalwindatlas.info/en/download/gis-files/",
    status: "offline_pipeline",
    access: "Public GIS downloads",
    coverage: "Long-term solar and wind resource potential",
    refresh: "Dataset release dependent",
    usedFor: "Future renewable-energy ranking",
    limitation: "Bankable energy assessment still needs on-site measurements and grid studies.",
  },
  {
    id: "minres",
    title: "Subsoil-use and mineral resources map",
    authority: "Ministry of Industry and Construction",
    category: "materials",
    url: "https://www.gov.kz/memleket/entities/mps/press/article/details/24754?lang=ru",
    status: "reference",
    access: "Official map and registries",
    coverage: "Licences, contracts and resource-management areas",
    refresh: "Registry dependent",
    usedFor: "Raw-material due diligence",
    limitation: "The site does not infer available reserves or access rights from nearby map objects.",
  },
];

export function sourceSummary() {
  return {
    total: dataSources.length,
    connected: dataSources.filter((source) => source.status === "connected").length,
    credentialsRequired: dataSources.filter((source) => source.status === "credentials_required").length,
    offlinePipeline: dataSources.filter((source) => source.status === "offline_pipeline").length,
    lastChecked: "2026-08-07",
  };
}
